image: maven:latest

stages:
  - build
  - test
  - clean

variables:
  GIT_DEPTH: "0"
  MAVEN_OPTS: "-DskipTests"
  SKIP_UI_TESTS: "true"

build:
  stage: build
  script:
    - "cd WordDetective"
    - "mvn clean install -Pskip-ui-tests"
    - "mvn compile"

checkstyle-test:
  stage: test
  script:
    - "cd WordDetective"
    - "mvn checkstyle:check"

spotbugs-test:
  stage: test
  script:
    - "cd WordDetective"
    - "mvn clean install -DskipTests"
    - "mvn spotbugs:spotbugs"

maven-test:
  stage: test
  script:
    - "cd WordDetective"
    - mvn test -Pskip-ui-tests

clean-up:
  stage: clean
  script:
    - "cd WordDetective"
    - "mvn clean"
