image: maven:3.8.3-openjdk-17

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode -P headless -DskipUiTests=true"

stages:
  - build
  - test
  - clean

cache:
  paths:
    - .m2/repository
  key: "$CI_BUILD_REF_NAME"

build:
  stage: build
  script:
    - "cd WordDetective; mvn clean install $MAVEN_CLI_OPTS"

maven-test:
  stage: test
  script:
    - "cd WordDetective; mvn clean test $MAVEN_CLI_OPTS"

spotbugs-test:
  stage: test
  script:
    - "cd WordDetective"
    - "mvn clean install $MAVEN_CLI_OPTS"
    - "mvn spotbugs:spotbugs"

checkstyle-test:
  stage: test
  script:
    - "cd WordDetective"
    - "mvn checkstyle:check"


clean-up:
  stage: clean
  script:
    - "cd WordDetective"
    - "mvn clean"
