image: maven:latest

stages:
  - build
  - test
  - clean

build:
  stage: build
  script:
    - "cd WordDetective"
    - "mvn clean install"
    # - "mvn clean install -U"
    # - "mvn compile"

checkstyle-test:
  stage: test
  script:
    - "cd WordDetective"
    - "mvn checkstyle:check"

maven-test:
  stage: test
  script:
    - "cd WordDetective"
    - mvn test

spotbugs-test:
  stage: test
  script:
    - "cd WordDetective"
    - "mvn clean install -U"
    - "mvn spotbugs:spotbugs"

clean-up:
  stage: clean
  script:
    - "cd WordDetective"
    - "mvn clean"
